Task3
AlexShmak/formal-lang-course pull request #3
Opened 2024-09-25 10:57 UTC by AlexShmak

2024-09-26 07:43 UTC, KubEF requested changes

2024-09-26 07:43 UTC, KubEF commented on project/task3.py
> +            return
Что это? Почему вам показалось, что возвращать `None` в конструкторе -- это хорошая идея? Что с математической точки зрения представляет собой объект, сконструированный от `None`? Это всё вопросы риторические.

Покуда вы всё равно сдали после дедлайна, и вам в смысле баллов это ничего не стоит, позволю себе попридираться.

2024-09-26 07:43 UTC, KubEF commented on project/task3.py
> +            return
А ещё у вас не все коммиты от нас подтянуты. Может быть вы из-за этого запутались?

2024-09-26 07:43 UTC, KubEF commented on project/task3.py
> +        return transitive_closure
Вроде бы вас просили реализовать это с помощью произведения матриц

2024-09-26 07:43 UTC, KubEF commented on project/task3.py
> +                print("Don't accept!")
🤨

2024-09-26 07:43 UTC, KubEF commented on project/task3.py
> +                print("Accepts!")
🤨

2024-09-27 07:49 UTC, AlexShmak commented on project/task3.py
> +        return transitive_closure
Исправил

2024-09-27 07:49 UTC, AlexShmak commented on project/task3.py
> +                print("Don't accept!")
Убрал

2024-09-27 07:49 UTC, AlexShmak commented on project/task3.py
> +                print("Accepts!")
Убрал

2024-09-27 07:58 UTC, KubEF approved these changes

2024-09-27 08:00 UTC, merged